- id: '1672858375016'
  alias: Ouverture Volet Lever
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - device_id: 17a014e2e3a6034079b0f55d5d56ca0f
    domain: cover
    entity_id: cover.volet_salon
    type: set_position
    position: 100
  mode: single
- id: '1672858702469'
  alias: Fermeture Volet Soir
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:00
  condition: []
  action:
  - if:
    - condition: or
      conditions:
      - condition: device
        device_id: d65adb7ef8988cc51cadf93952a717c8
        domain: device_tracker
        entity_id: device_tracker.cph2399
        type: is_home
      - condition: device
        device_id: 2895e1137403e2f6b7eb238bbc79c9f6
        domain: device_tracker
        entity_id: device_tracker.m2003j15sc
        type: is_home
    then:
    - type: turn_on
      device_id: b50a528b38b49b0e8ee89a8550736b1e
      entity_id: 77bad382b924c8ada9c18ca80d26b803
      domain: light
  - wait_for_trigger:
    - platform: sun
      event: sunset
      offset: +00:20:00
  - device_id: 17a014e2e3a6034079b0f55d5d56ca0f
    domain: cover
    entity_id: cover.volet_salon
    type: set_position
    position: 0
    enabled: true
  mode: single
- id: '1673739340001'
  alias: Allumer PC Backlight
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.m3te0r_satellite_last_system_state_changed
    from: unavailable
    to: SessionUnlock
  - platform: state
    entity_id:
    - sensor.m3te0r_satellite_last_system_state_changed
    to: SessionUnlock
    from: SessionLock
  - platform: state
    entity_id:
    - sensor.m3te0r_affichage_display_count
    from: '1'
    to: '2'
  condition: []
  action:
  - type: turn_on
    device_id: ed846cfca5fd4bb6829e9769e07b9e27
    entity_id: light.ruban_led_rgb_pc_backlight
    domain: light
  mode: single
- id: '1673739436046'
  alias: Eteindre PC Backlight
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.m3te0r_satellite_last_system_state_changed
    to: unavailable
  - platform: state
    entity_id:
    - sensor.m3te0r_satellite_last_system_state_changed
    to: SessionLock
  - platform: state
    entity_id:
    - sensor.m3te0r_affichage_display_count
    from: '2'
    to: '1'
  condition: []
  action:
  - type: turn_off
    device_id: ed846cfca5fd4bb6829e9769e07b9e27
    entity_id: light.ruban_led_rgb_pc_backlight
    domain: light
  mode: single
- id: '1673822043960'
  alias: Lumière Mouvement Couloir Cuisine-Salon
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.capteur_mouvement_1_occupancy
    from: 'off'
    to: 'on'
  condition:
  - condition: sun
    before: sunrise
    after: sunset
    enabled: true
  action:
  - type: turn_on
    device_id: 10426913e21cbe7addfda0fbd154bc5d
    entity_id: light.ampoule_w_couloir_cuisine_salon
    domain: light
  - wait_for_trigger:
    - platform: state
      entity_id:
      - binary_sensor.capteur_mouvement_1_occupancy
      from: 'on'
      to: 'off'
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 10426913e21cbe7addfda0fbd154bc5d
    entity_id: light.ampoule_w_couloir_cuisine_salon
    domain: light
  mode: single
- id: '1674518929675'
  alias: Speedtest update interval
  description: Speedtest durchführen
  trigger:
  - platform: time
    at: '23:00:00'
    enabled: false
  - platform: time
    at: 07:00:00
    enabled: false
  - platform: time
    at: '15:00:00'
    enabled: false
  condition: []
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: sensor.speedtest_download
  mode: single
- id: '1676853805476'
  alias: Internet Speed Glow Connect Great
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.speedtest_download'')|float >= 10 }}'
  action:
  - service: shell_command.green
- id: '1689715410941'
  alias: Enable/Disable wallpanel charging
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.android_bluedroid_batterie
    below: 25
    id: below
  - platform: numeric_state
    entity_id: sensor.android_bluedroid_batterie
    above: 90
    id: above
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - below
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          device_id: 86b32369f4192c320d4d20d6a84ae7de
    - conditions:
      - condition: trigger
        id:
        - above
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          device_id: 86b32369f4192c320d4d20d6a84ae7de
  mode: single
- id: '1689719352340'
  alias: Wallpanel screen on motion
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.capteur_mouvement_salon_occupancy
    to: 'on'
    id: motion_living_room_detected
  - platform: state
    entity_id:
    - binary_sensor.capteur_mouvement_salon_occupancy
    to: 'off'
    id: motion_living_room_non_detected
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - motion_living_room_detected
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.android_bluedroid_screen
    - conditions:
      - condition: trigger
        id:
        - motion_living_room_non_detected
      sequence:
      - delay:
          hours: 0
          minutes: 1
          seconds: 0
          milliseconds: 0
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.android_bluedroid_screen
  mode: single
