- id: '1672858375016'
  alias: Ouverture Volet Lever
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - device_id: 17a014e2e3a6034079b0f55d5d56ca0f
    domain: cover
    entity_id: cover.volet_salon
    type: set_position
    position: 100
  mode: single
- id: '1672858702469'
  alias: Fermeture Volet Soir
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:00
  condition: []
  action:
  - if:
    - condition: or
      conditions:
      - condition: device
        device_id: d65adb7ef8988cc51cadf93952a717c8
        domain: device_tracker
        entity_id: device_tracker.cph2399
        type: is_home
      - condition: device
        device_id: 2895e1137403e2f6b7eb238bbc79c9f6
        domain: device_tracker
        entity_id: device_tracker.m2003j15sc
        type: is_home
    then:
    - service: light.turn_on
      data: {}
      target:
        entity_id: light.lumieres_salon_1_lampadaire_canape
  - wait_for_trigger:
    - platform: sun
      event: sunset
      offset: +00:20:00
  - device_id: 17a014e2e3a6034079b0f55d5d56ca0f
    domain: cover
    entity_id: cover.volet_salon
    type: set_position
    position: 0
    enabled: true
  mode: single
- id: '1673739340001'
  alias: Allumer PC Backlight
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.m3te0r_satellite_last_system_state_changed
    from: unavailable
    to: SessionUnlock
  - platform: state
    entity_id:
    - sensor.m3te0r_satellite_last_system_state_changed
    to: SessionUnlock
    from: SessionLock
  - platform: state
    entity_id:
    - sensor.m3te0r_affichage_display_count
    from: '1'
    to: '2'
  condition: []
  action:
  - type: turn_on
    device_id: ed846cfca5fd4bb6829e9769e07b9e27
    entity_id: light.ruban_led_rgb_pc_backlight
    domain: light
  mode: single
- id: '1673739436046'
  alias: Eteindre PC Backlight
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.m3te0r_satellite_last_system_state_changed
    to: unavailable
  - platform: state
    entity_id:
    - sensor.m3te0r_satellite_last_system_state_changed
    to: SessionLock
  - platform: state
    entity_id:
    - sensor.m3te0r_affichage_display_count
    from: '2'
    to: '1'
  condition: []
  action:
  - type: turn_off
    device_id: ed846cfca5fd4bb6829e9769e07b9e27
    entity_id: light.ruban_led_rgb_pc_backlight
    domain: light
  - type: turn_off
    device_id: 3cf59aae4dab4736703593ce385e5109
    entity_id: 82de55f8c607126dfd37b8eac710244f
    domain: light
  mode: single
- id: '1689715410941'
  alias: Enable/Disable wallpanel charging
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.android_bluedroid_batterie
    below: 25
    id: below
  - platform: numeric_state
    entity_id: sensor.android_bluedroid_batterie
    above: 90
    id: above
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - below
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          device_id: 86b32369f4192c320d4d20d6a84ae7de
    - conditions:
      - condition: trigger
        id:
        - above
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          device_id: 86b32369f4192c320d4d20d6a84ae7de
  mode: single
- id: '1689719352340'
  alias: Wallpanel screen on motion
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.capteur_mouvement_salon_occupancy
    to: 'on'
    id: motion_living_room_detected
  - platform: state
    entity_id:
    - binary_sensor.capteur_mouvement_salon_occupancy
    to: 'off'
    id: motion_living_room_non_detected
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - motion_living_room_detected
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.android_bluedroid_screen
    - conditions:
      - condition: trigger
        id:
        - motion_living_room_non_detected
      sequence:
      - delay:
          hours: 0
          minutes: 1
          seconds: 0
          milliseconds: 0
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.android_bluedroid_screen
  mode: single
- id: '1697749826124'
  alias: Lessive - Notif
  description: ''
  use_blueprint:
    path: sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.prise_lave_linge_power
      starting_threshold: 10
      starting_hysteresis: 4
      finishing_threshold: 8
      actions:
      - service: notify.mobile_app_cph2399
        data:
          message: Lessive terminée
          data:
            persistent: true
            tag: washing_machine
            actions:
            - action: EMPTY_DONE
              title: "\U0001F9FAOK c'est vidé!"
      - wait_for_trigger:
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: EMPTY_DONE
        continue_on_timeout: false
        enabled: true
      - service: notify.mobile_app_cph2399
        data:
          message: clear_notification
          data:
            tag: washing_machine
        enabled: true
      pre_actions:
      - service: notify.mobile_app_cph2399
        data:
          message: "Lessive lancée \U0001F9FC"
          title: Machine goes BRRRRRR
      finishing_hysteresis: 4
- id: '1698104816067'
  alias: Interrupteur salon
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 5fa2be6378cc51520f7eda3fb986a5a1
    type: action
    subtype: single_left
    discovery_id: 0x54ef441000905c8b action_single_left
    id: Switch single left
  - platform: device
    domain: mqtt
    device_id: 5fa2be6378cc51520f7eda3fb986a5a1
    type: action
    subtype: single_right
    discovery_id: 0x54ef441000905c8b action_single_right
    id: Switch single right
  - platform: device
    domain: mqtt
    device_id: 5fa2be6378cc51520f7eda3fb986a5a1
    type: action
    subtype: double_right
    discovery_id: 0x54ef441000905c8b action_double_right
    id: Switch double right
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Switch single left
      sequence:
      - type: toggle
        device_id: 2e1de49063ad9eac1c96d4b03de00e5f
        entity_id: c01083ea11ea1a1504b53075f6477fbd
        domain: switch
    - conditions:
      - condition: trigger
        id:
        - Switch single right
      sequence:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.lumieres_salon_1_lampadaire_canape
    - conditions:
      - condition: trigger
        id:
        - Switch double right
      sequence:
      - type: toggle
        device_id: ff95c4db92b2b3b8ddef2b1809c4dc74
        entity_id: d2c6bb222621973cfe3e9731cf9f0bb0
        domain: light
  mode: single
- id: '1698179412256'
  alias: 'Scene 1 allume salon '
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: db5f32646e7214ce5c77c956ccacc519
    type: action
    subtype: 1_single
    discovery_id: 0x84fd27fffec22f47 action_1_single
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.lumieres_salon_1_lampadaire_canape
  mode: single
- id: '1700085345446'
  alias: Ouverture porte d'entrée - Lumières
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.capteur_mouvement_chambre_sol_occupancy
      light_switch:
        entity_id: scene.lumieres_allumee
      time_delay: 0
      light_transition_on: 5
      include_light_control:
      - use_transition
      light_transition_off: 20
      end_scenes:
      - scene.ouverture_porte_entree_lumiere_couloir_eteinte
      include_sun: sun_enabled
      sun_elevation: -1.5
      zone: zone.home
      people:
      - person.marie
      include_device_tracker: zone_people_enabled
- id: '1700090409115'
  alias: Lumière Mouvement Couloir Cuisine-Salon2
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.capteur_mouvement_1_occupancy
      light_switch:
        entity_id: light.interrupteur_aqara_entree_left
      time_delay: 1
      include_sun: sun_enabled
- id: '1700176345431'
  alias: La balise Alarme NFC est analysée
  description: ''
  trigger:
  - platform: tag
    tag_id: 56ba0b06-35f3-45e9-a2e0-914eb485f25b
  condition: []
  action:
  - service: alarm_control_panel.alarm_disarm
    data:
      code: '1127'
    target:
      device_id: 44e2b6977448b5f2e973c5bd39d8e08d
  - service: alarm_control_panel.alarm_arm_home
    data:
      code: '1127'
    target:
      device_id: 44e2b6977448b5f2e973c5bd39d8e08d
  mode: single
- id: '1700178023441'
  alias: Allumer Bureau Matin
  description: ''
  trigger:
  - platform: time
    at: 09:30:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.wol_thinkpad_mathieu
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.wol_m3te0r_pc
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.switch_bureau
  mode: single
