# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

media_player:
  - platform: yamaha
    host: 192.168.2.28

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
