# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  allowlist_external_dirs:
    - /config
  customize:
    zone.home:
      radius: 70

recorder:
  purge_keep_days: 200
  exclude:
    entities:
      - climate.thermostat
      - lock.thermostat_child_lock
      - number.thermostat_deadzone_temperature
      - number.thermostat_local_temperature_calibration
      - number.thermostat_max_temperature_limit
      - number.thermostat_min_temperature_limit
      - select.thermostat_sensor
      - switch.ruban_led_rgb_pc_backlight_do_not_disturb
      - select.ruban_led_rgb_pc_backlight_color_power_on_behavior
      - media_player.m3te0r
      - select.prise_bureau_serveur_pc_equipements_power_outage_memory
      - select.prise_bureau_serveur_pc_equipements_indicator_mode
      - lock.prise_bureau_serveur_pc_equipements_child_lock
      - update.prise_bureau_serveur_pc_equipements
      - switch.lampe_rgbw_bureau_pc_do_not_disturb
      - select.lampe_rgbw_bureau_pc_color_power_on_behavior
      - switch.prise_bureau_serveur_pc_equipements
      - sensor.android_bluedroid_free_memory
      - switch.prise_lave_linge
      - select.prise_lave_linge_power_outage_memory
      - select.prise_lave_linge_indicator_mode
      - lock.prise_lave_linge_child_lock
      - update.prise_lave_linge
      - select.prise_2_power_outage_memory
      - select.prise_2_indicator_mode
      - lock.prise_2_child_lock
      - update.prise_2
      - sensor.android_bluedroid_internal_storage_free_space

# Text to speech
tts:
  - platform: google_translate

media_player:
  - platform: yamaha
    host: 192.168.2.28

expose_camera_stream_source:

wake_on_lan:

readme:

switch:
  - platform: wake_on_lan
    mac: 30:85:a9:94:57:7b
    host: "192.168.2.2"
    name: WOL M3te0r PC
    turn_off:
      service: script.shutdown_pc_m3te0r
  - platform: wake_on_lan
    mac: 00:a0:de:de:2e:a8
    name: WOL Yamaha R-N500
  - platform: wake_on_lan
    mac: b4:22:00:72:d3:57
    name: WOL Imprimante
  - platform: wake_on_lan
    mac: a4:4c:c8:73:56:7a
    name: WOL Marie Laptop
  - platform: wake_on_lan
    mac: 8c:8c:aa:74:df:f0
    name: WOL Thinkpad Mathieu
  - platform: wake_on_lan
    mac: 00:11:32:8c:51:87
    name: WOL DS1618+ NAS

sensor:
  - platform: template
    sensors:
      freebox_download_speed_mbytes_per_sec:
        friendly_name: "Download speed"
        value_template: "{{ (states('sensor.freebox_download_speed') | float / 1000) | round(3) }}"
        unit_of_measurement: MB/s
        device_class: data_rate
      freebox_upload_speed_mbytes_per_sec:
        friendly_name: "Uppload speed"
        value_template: "{{ (states('sensor.freebox_upload_speed') | float / 1000) | round(3) }}"
        unit_of_measurement: MB/s
        device_class: data_rate
      outside_temperature:
        friendly_name: "outside_temperature"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('weather.bordeaux', 'temperature') }}"
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
      - "time_date"
      - "time_utc"
      - "beat"
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: disk_use
      - type: disk_free
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: swap_use_percent
      - type: swap_use
      - type: swap_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: network_in
        arg: end0
      - type: network_out
        arg: end0
      - type: throughput_network_in
        arg: end0
      - type: throughput_network_out
        arg: end0
      - type: packets_in
        arg: end0
      - type: packets_out
        arg: end0
      - type: ipv4_address
        arg: end0
      - type: ipv6_address
        arg: end0
      - type: processor_use
      - type: processor_temperature
      - type: last_boot

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.2.40
    - 192.168.2.125

bluetooth:

fastdotcom:
  scan_interval:
    hours: 12

powercalc:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
