# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

homeassistant:
  allowlist_external_dirs:
    - /config
    - /config/www
  customize:
    zone.home:
      radius: 60

recorder:
  purge_keep_days: 60
  exclude:
    domains:
      #- automation
      - update
      #- script
      - image
      - camera
    entity_globs:
      - sensor.shopping_list_with_grocy*
      - sensor.too_good_to_go*
      - sensor.*uptime*
      - sensor.*_internal_temperature
    entities:
      - climate.thermostat
      - lock.thermostat_child_lock
      - number.thermostat_deadzone_temperature
      - number.thermostat_local_temperature_calibration
      - number.thermostat_max_temperature_limit
      - number.thermostat_min_temperature_limit
      - select.thermostat_sensor
      - switch.ruban_led_rgb_pc_backlight_do_not_disturb
      - select.ruban_led_rgb_pc_backlight_color_power_on_behavior
      - media_player.m3te0r
      - select.prise_bureau_serveur_pc_equipements_power_outage_memory
      - select.prise_bureau_serveur_pc_equipements_indicator_mode
      - lock.prise_bureau_serveur_pc_equipements_child_lock
      - update.prise_bureau_serveur_pc_equipements
      - switch.lampe_rgbw_bureau_pc_do_not_disturb
      - select.lampe_rgbw_bureau_pc_color_power_on_behavior
      - switch.prise_bureau_serveur_pc_equipements
      - sensor.android_bluedroid_free_memory
      - switch.prise_lave_linge
      - select.prise_lave_linge_power_outage_memory
      - select.prise_lave_linge_indicator_mode
      - lock.prise_lave_linge_child_lock
      - update.prise_lave_linge
      - select.prise_2_power_outage_memory
      - select.prise_2_indicator_mode
      - lock.prise_2_child_lock
      - update.prise_2
      - sensor.android_bluedroid_internal_storage_free_space
      - sensor.capteur_salon_s3_mini_still_energy
      - sensor.capteur_salon_s3_mini_still_distance
      - sensor.capteur_presence_bureau_s3_mini_still_energy
      - sensor.capteur_presence_bureau_s3_mini_detection_distance
      - sensor.capteur_presence_bureau_s3_mini_stil_distance
      - sensor.capteur_presence_bureau_s3_mini_moving_distance
      - sensor.capteur_presence_bureau_s3_mini_still_distance
      - sensor.capteur_presence_ld2450_bureau_target_1_direction
      - sensor.capteur_presence_ld2450_bureau_target_1_speed
      - sensor.capteur_presence_ld2450_bureau_target_1_x
      - sensor.capteur_presence_ld2450_bureau_target_1_y
      - sensor.capteur_presence_ld2450_bureau_target_1_distance
      - sensor.capteur_presence_ld2450_bureau_target_1_angle
      - sensor.capteur_presence_salon_still_energy
      - sensor.capteur_ld2450_entree_bis_target_1_x_2
      - sensor.capteur_ld2450_entree_bis_target_1_y_2
      - sensor.capteur_ld2450_entree_bis_target_1_distance_2
      - sensor.capteur_ld2450_entree_bis_target_1_angle_2
      - sensor.capteur_ld2450_entree_bis_target_1_speed_2
      - sensor.ld2450_bureau_53l3cu5_target1_x
      - sensor.ld2450_bureau_53l3cu5_target1_y
      - sensor.ld2450_bureau_53l3cu5_target1_angle
      - sensor.capteur_presence_bureau_s3_mini_move_energy
      - sensor.a1_03919c440501678_signal_wi_fi
      - sensor.ld2450_bureau_53l3cu5_target1_position
      - image.a1_03919c440501678_camera
      - sensor.ld2450_bureau_53l3cu5_target1_speed
      - sensor.ld2450_bureau_53l3cu5_zone2_target_counts
      - sensor.packets_out_end0
      - sensor.packets_in_end0
      - sensor.watchman_missing_entities
      - sensor.watchman_missing_services
      - sensor.watchman_last_updated
      - sensor.products_shopping_list_with_grocy
      - sensor.shopping_list_shopping_list_with_grocy
      - sensor.network_in_end0
      - sensor.network_out_end0
      - sensor.ipv4_address_end0
      - sensor.ipv6_address_end0
      - sensor.memory_free
      - sensor.time_utc
      - sensor.time_date
      - sensor.time
      - sensor.date_time_utc
      - sensor.date_time_iso
      - sensor.date_time
      - sensor.ld2450_bureau_53l3cu5_target2_x
      - sensor.ld2450_bureau_53l3cu5_target2_y
      - sensor.ld2450_bureau_53l3cu5_target2_angle
      - sensor.capteur_ens160_s3_mini_uptime
      - sensor.ld2450_bureau_53l3cu5_zone1_target_counts
      - sensor.flexispot_2_uptime
      - binary_sensor.capteur_presence_bureau_s3_mini_moving_target
      - sensor.load_5m
      - sensor.load_15m
      - sensor.redmi_note_9_free_memory
      - sensor.capteur_ens160_s3m_2_uptime
      - sensor.flexispot_2_wifi_signal
      - sensor.backup_state
      - sensor.bordeaux_next_rain
      - sensor.m3te0r_audio_sessions
      - sensor.network_throughput_in_end0
      - sensor.network_throughput_out_end0
      - sensor.myenedis_50080550746371_production
      - sensor.myenedis_50080550746371_ecowatt
      - sensor.myenedis_history_50080550746371_hp
      - sensor.myenedis_history_50080550746371_hc
      - sensor.radarr_disk_space_movies
      - sensor.capteur_ens160_s3_mini_internal_temperature
      - fan.a1_03919c440501678_ventilateur_auxiliaire
      - sensor.a1_03919c440501678_vitesse_du_ventilateur_auxiliaire
      - fan.a1_03919c440501678_ventilateur_de_refroidissement
      - sensor.a1_03919c440501678_vitesse_du_ventilateur_de_refroidissement
      - sensor.capteur_ens160_s3_mini_temperature
      - sensor.ld2450_bureau_53l3cu5_target2_position
      - sensor.capteur_ens160_s3m_2_humidity
      - sensor.capteur_ld2450_entree_bis_internal_temperature
      - sensor.capteur_ens160_s3m_2_temperature
      - sensor.m3te0r_audio_peak_volume
      - sensor.ld2450_bureau_53l3cu5_target1_direction
      - sensor.flexispot_2_internal_temperature
      - sensor.capteur_ld2450_entree_bis_uptime_sensor
      - sensor.tv_ambilight_courant_estime
      - sensor.capteur_presence_bureau_s3_mini_uptime_sensor
      - sensor.capteur_presence_bureau_s3_mini_internal_temperature
      - sensor.a1_03919c440501678_vitesse_du_ventilateur_de_l_isolateur_thermique
      - sensor.a1_03919c440501678_temperature_de_la_buse
      - sensor.a1_03919c440501678_temperature_du_lit
      - sensor.capteur_ld2450_entree_bis_target_2_x_2
      - sensor.capteur_ld2450_entree_bis_target_2_y_2
      - sensor.capteur_ld2450_entree_bis_target_2_distance_2
      - sensor.capteur_ld2450_entree_bis_zone_3_target_count
      - sensor.m3te0r_memory_used
      - sensor.m3te0r_stockage_c_2
      - sensor.m3te0r_charge_cpu
      - sensor.opnsense_interface_lan_inpkts_packets_per_second
      - sensor.opnsense_interface_lan_outpkts_packets_per_second
      - sensor.capteur_ens160_s3m_2_internal_temperature
      - sensor.opnsense_interface_wan_outpkts_packets_per_second
      - sensor.opnsense_system_load_average_one_minute
      - sensor.opnsense_interface_wan_inpkts_packets_per_second
      - sensor.opnsense_gateway_wan_gwv6_stddev
      - sensor.opnsense_gateway_wan_gw_stddev
      - sensor.opnsense_system_load_average_five_minute
      - sensor.opnsense_gateway_wan_gw_delay
      - sensor.opnsense_gateway_wan_gwv6_delay

# Text to speech
tts:
  - platform: google_translate

media_player:
  - platform: yamaha
    host: 192.168.2.28

expose_camera_stream_source:

wake_on_lan:

readme:

switch:
  - platform: wake_on_lan
    mac: 30:85:a9:94:57:7b
    host: "192.168.2.2"
    name: WOL M3te0r PC
    turn_off:
      service: script.shutdown_pc_m3te0r
  - platform: wake_on_lan
    mac: 00:a0:de:de:2e:a8
    name: WOL Yamaha R-N500
  - platform: wake_on_lan
    mac: b4:22:00:72:d3:57
    name: WOL Imprimante
  - platform: wake_on_lan
    mac: a4:4c:c8:73:56:7a
    name: WOL Marie Laptop
  - platform: wake_on_lan
    mac: 8c:8c:aa:74:df:f0
    name: WOL Thinkpad Mathieu
  - platform: wake_on_lan
    mac: 00:11:32:8c:51:87
    name: WOL DS1618+ NAS

sensor:
  - platform: template
    sensors:
      freebox_download_speed_mbytes_per_sec:
        friendly_name: "Download speed"
        value_template: "{{ (states('sensor.freebox_download_speed') | float / 1000) | round(3) }}"
        unit_of_measurement: MB/s
        device_class: data_rate
      freebox_upload_speed_mbytes_per_sec:
        friendly_name: "Uppload speed"
        value_template: "{{ (states('sensor.freebox_upload_speed') | float / 1000) | round(3) }}"
        unit_of_measurement: MB/s
        device_class: data_rate
      outside_temperature:
        friendly_name: "outside_temperature"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('weather.bordeaux', 'temperature') }}"
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
      - "time_date"
      - "time_utc"

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.2.40
    - 192.168.2.125

bluetooth:

powercalc:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
